// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  products_grid: dynamic(() => import("./ProductsGrid")),
  slide: dynamic(() => import("./Slide")),
  team_section: dynamic(() => import("./TeamSection")),
  video_block: dynamic(() => import("./VideoBlock")),
};
